In [1]:
import numpy as np

In [2]:
print(np.__version__)

1.18.5


In [3]:
my_list = [1,2,3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
arr = np.array(my_list)
print(arr)

[1 2 3]


In [6]:
my_list_2 = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
arr_2 = np.array(my_list_2)

In [8]:
arr_2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [2]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [2]:
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [4]:
np.random.rand(5,5)

array([[0.93324559, 0.27585567, 0.64381557, 0.07197934, 0.93916652],
       [0.94088195, 0.38167871, 0.9955482 , 0.61827468, 0.98213017],
       [0.25113641, 0.8937509 , 0.43482504, 0.33541587, 0.54200235],
       [0.49181021, 0.56128688, 0.99604894, 0.28151403, 0.41982511],
       [0.5129877 , 0.03411726, 0.42309033, 0.54843294, 0.46632787]])

In [8]:
np.random.randn(2,5)

array([[ 0.19399915,  0.409122  ,  0.27423773,  0.57441785,  0.87380145],
       [-0.54763193, -0.61567248,  0.94830825, -0.6474969 , -0.30219252]])

In [6]:
np.random.randint(1,100,10)

array([97,  4,  9, 60, 95, 54, 13, 34, 68, 86])

In [3]:
arr = np.arange(25)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [12]:
ranarr = np.random.randint(0,100,10)
ranarr

array([89, 58, 74, 83, 37, 54, 40, 19, 43, 60])

In [13]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [14]:
ranarr.max()

89

In [15]:
ranarr.min()

19

In [16]:
ranarr.argmax()

0

In [17]:
ranarr.argmin()

7

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [5]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [6]:
arr.shape

(25,)

In [7]:
arr.reshape(1,25).shape

(1, 25)

In [11]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [21]:
arr.dtype

dtype('int32')

In [22]:
from numpy.random import randn
randn(5,3)

array([[ 0.49752037,  2.18077869, -0.18741583],
       [-0.53145664,  1.18931389,  0.72238137],
       [ 0.45223707,  0.44263855,  0.04116961],
       [ 0.69357985, -1.37341705, -0.49054103],
       [ 0.85469556, -1.06070696, -0.69696447]])