In [2]:
import numpy as np

In [2]:
arr = np.arange(0,21,2)

In [3]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr[5]

10

In [5]:
ranarr = np.random.randint(0,101,20)

In [6]:
ranarr

array([45, 17, 70, 84, 30, 62, 95,  0, 21, 35, 23, 50, 41, 23, 57, 47, 84,
       60, 52, 86])

In [7]:
arr_2 = ranarr[4:18:2]
arr_2

array([30, 95, 21, 23, 41, 57, 84])

In [8]:
ranarr[5:]

array([62, 95,  0, 21, 35, 23, 50, 41, 23, 57, 47, 84, 60, 52, 86])

In [9]:
ranarr[:9]

array([45, 17, 70, 84, 30, 62, 95,  0, 21])

In [3]:
arr = np.arange(0,11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[0:5] = 100

In [6]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [2]:
arr = np.arange(0,11)

# # # # # # broadcasting

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
slice_of_arr = arr[0:6]

In [5]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [6]:
slice_of_arr[:] #[:] means all elements

array([0, 1, 2, 3, 4, 5])

In [8]:
slice_of_arr[:] = 99

In [9]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [10]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [11]:
arr_copy = arr.copy()

In [12]:
arr
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [13]:
arr_copy[:] = 100

In [14]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [15]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

# # # # matrices

In [3]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [4]:
arr_2d[2][1]

40

In [5]:
arr_2d[2,1]

40

In [6]:
arr_2d[:2,1:] #[:2] = grab every row except row 2, [1:] = grab every column beginning with column 1

array([[10, 15],
       [25, 30]])

In [7]:
arr_2d[1:]

array([[20, 25, 30],
       [35, 40, 45]])

In [8]:
arr_2d[1:,:2]

array([[20, 25],
       [35, 40]])

In [24]:
## it's different from using [][], so [row,col] is recommended using
arr_2d[1:][:2]

array([[20, 25, 30],
       [35, 40, 45]])

# # #

In [25]:
arr_2d = np.zeros((10,10))

In [38]:
arr_length = arr_2d.shape
arr_length

(10, 10)

In [39]:
arr_length = arr_2d.shape[0]
arr_length

10

In [27]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [40]:
for i in range(arr_length):
    arr_2d[i] = i
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [41]:
arr_2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

# # # #

In [42]:
a = np.array([1,2,3])
a

array([1, 2, 3])

In [43]:
a = np.array(a, dtype='f')
a

array([1., 2., 3.], dtype=float32)

# # # #

In [44]:
arr = np.arange(1,11)

In [45]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [46]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [47]:
bool_arr = arr > 5

In [48]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [49]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [51]:
# short term
arr[arr>5]

array([ 6,  7,  8,  9, 10])

## practise

In [54]:
arr = np.arange(50).reshape(5,10)

In [55]:
arr

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [77]:
print(arr.shape[0])
print(arr.shape[1])

5
10


In [78]:
arr[arr%5==0].reshape(arr.shape[0],arr.shape[1]//5)

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [82]:
arr[1:4, 2:6]

array([[12, 13, 14, 15],
       [22, 23, 24, 25],
       [32, 33, 34, 35]])

In [93]:
arr_2 = arr[arr %2 ==0].reshape(5,5)
arr_2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [94]:
arr_2[:1,:].reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [96]:
arr_2[:, 2:3].reshape(1,5)

array([[ 4, 14, 24, 34, 44]])

In [97]:
print("very good Pice")

very good Pice


In [101]:
print("please be the better person for yourself and others, and bear in mind that I love myself")

please be the better person for yourself and others, and bear in mind that I love myself
